### ISSUE TITLE
Possible Debug Options?

### ISSUE THREAD

**Issue by kashalls** [daniela-hase/onvif-server#2]
Is there any debug options possible? I was trying to get a rtsp stream from [go2rtc](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-ffmpeg-device) to convert a h264 stream from a USB Camera to RTSP and using this to wrap it for UniFi Protect. Protect see's the camera, but it is hard stuck on the snapshot image. Shows as H264 stream, not sure what to go from here.

![9yCQMgU](https://github.com/user-attachments/assets/df150bf2-a823-473c-8581-ba8caa38941d)
![image](https://github.com/user-attachments/assets/40aa27c8-d2ba-4000-9f57-f232beddaf82)

**Comment by kashalls** [comment]
`config.yaml`
```yaml
onvif:
  - mac: d8:3a:dd:15:83:a9
    ports:
      server: 8081                                # The port for the server to run on
      rtsp: 8554                                  # The port for the stream passthrough, leave this at 8554
    name: MyRTSPStream                            # A user define name
    uuid: 1714a629-ebe6-4bb8-a430-c18ffd8fa5f6    # A randomly chosen UUID (see below)
    highQuality:
      rtsp: /usb2?mp4                           # The RTSP Path
      width: 1280                                 # The Video Width
      height: 720                                # The Video Height
      framerate: 10                               # The Video Framerate/FPS
      bitrate: 1024                               # The Video Bitrate in kb/s
      quality: 4                                  # Quality, leave this as 4 for the high quality stream.
    lowQuality:
      rtsp: /usb2?mp4                           # The RTSP Path
      width: 1280                                 # The Video Width
      height: 720                                # The Video Height
      framerate: 10                               # The Video Framerate/FPS
      bitrate: 1024                               # The Video Bitrate in kb/s
      quality: 1                                  # Quality, leave this as 1 for the low quality stream.
    target:
      hostname: 127.0.0.1                      # The Hostname of the RTSP stream
      ports:
        rtsp: 5546                                 # The Port of the RTSP stream

```

`go2rtc.yaml`
```yaml
streams:
  usb2: ffmpeg:device?video=/dev/video0&video_size=1280x720#video=h264#hardware
rtsp:
  listen: ":5546"
```
